// node lesson04-JS-array-object-loops/src/arrays.js
const arrayNumbers = [1, 2, 3, 4, 5, 6];
const arrayStrings = ['one', 'two', 'three', 'four', 'five', 'six'];
const arrayBoolean = [true, false, true, false, true];
const arrayMixed = [1, 'two', true, false, [1, 2, 3], { name: 'John', age: 30 }];
const arrayMixed2 = [1, '2', true, null, undefined, { key: 'value' }, [1, 2, 3]];
console.log('forEachArrayNumbers');
arrayNumbers.forEach((item, index) => console.log(`index ${index}, value ${item}`));
console.log('forEachArrayStrings');
arrayStrings.forEach((item, index) => console.log(`index ${index}, value ${item}`));
console.log('forEachArrayBoolean');
arrayBoolean.forEach((item, index) => console.log(`index ${index}, value ${item}`));
console.log('forEachArrayMixed');
arrayMixed.forEach((item, index) => console.log(`index ${index}, value ${item}`));
console.log('forEachArrayMixed2');
arrayMixed2.forEach((item, index) => console.log(`index ${index}, value ${item}`));
console.log('-------- ArrayStrings --------');
const mapArrayStringsToUpperCase = arrayStrings.map((item) => item.toUpperCase());
console.log('mapArrayStringsToUpperCase', mapArrayStringsToUpperCase);
const filterArrayStrings = arrayStrings.filter((item) => item.length > 3);
console.log('filterArrayStrings', filterArrayStrings);
const getArrayStringsSumByReduce = arrayStrings.reduce((acc, item) => acc + item, '');
console.log('getArrayStringsSumByReduce', getArrayStringsSumByReduce);
console.log('-------- ArrayNumbers --------');
arrayNumbers.push(7);
console.log('pushArrayNumbers', arrayNumbers);
arrayNumbers.pop();
console.log('popArrayNumbers', arrayNumbers);
arrayNumbers.unshift(0);
console.log('unshiftArrayNumbers', arrayNumbers);
arrayNumbers.shift();
console.log('shiftArrayNumbers', arrayNumbers);
arrayNumbers.splice(2, 0, 2.5); //insert 2.5 in index 2 and delete 0 elements
console.log('spliceArrayNumbersInsert', arrayNumbers);
arrayNumbers.splice(2, 1);
console.log('spliceArrayNumbersDelete', arrayNumbers);
arrayNumbers.reverse();
console.log('reverseArrayNumbers', arrayNumbers);
arrayNumbers.sort(); // accending order
console.log('sortArrayNumbersDefault', arrayNumbers);
arrayNumbers.sort((a, b) => b - a); // decending order
console.log('sortArrayNumbersDecending', arrayNumbers);
arrayNumbers.sort((a, b) => a - b); // accending order
console.log('sortArrayNumbersAccending', arrayNumbers);
const mapArrayNumbers = arrayNumbers.map((item) => item * 2);
console.log('mapArrayNumbers', mapArrayNumbers);
const getArrayNumbersSumByReduce = arrayNumbers.reduce((acc, item) => acc + item, 0);
console.log('getArrayNumbersSumByReduce', getArrayNumbersSumByReduce);
const getArrayNumbersElementByIndex = arrayNumbers.at(2);
console.log('getArrayNumbersElementByIndex', getArrayNumbersElementByIndex);
const getArrayNumbersLength = arrayNumbers.length;
console.log('getArrayNumbersLength', getArrayNumbersLength);
const getArrayNumbersLastElement = arrayNumbers[arrayNumbers.length - 1];
console.log('getArrayNumbersLastElement', getArrayNumbersLastElement);
const findArrayNumbersElement = arrayNumbers.find((item) => item > 5);
console.log('findArrayNumbersElement', findArrayNumbersElement);
const findArrayNumbersIndex = arrayNumbers.findIndex((item) => item > 5);
console.log('findArrayNumbersIndex', findArrayNumbersIndex);
const includesArrayNumbers = arrayNumbers.includes(3);
console.log('includesArrayNumbers', includesArrayNumbers);
const everyArrayNumbers = arrayNumbers.every((item) => typeof item === 'number');
console.log('everyArrayNumbers', everyArrayNumbers);
const someArrayNumbers = arrayNumbers.some((item) => item % 2 === 0);
console.log('someArrayNumbers', someArrayNumbers);
const filteredArrayNumbers = arrayNumbers.filter((item) => item % 2 === 0);
console.log('filteredArrayNumbers', filteredArrayNumbers);
const indexOfArrayNumbers = arrayNumbers.indexOf(3);
console.log('indexOfArrayNumbers', indexOfArrayNumbers);
const stringedArrayNumbers = arrayNumbers.toString();
console.log('stringedArrayNumbers', stringedArrayNumbers);
const joinedArrayNumbers = arrayNumbers.join(',');
console.log('joinedArrayNumbers', joinedArrayNumbers);
const slicedArrayNumbers = arrayNumbers.slice(1, 4);
console.log('slicedArrayNumbers', slicedArrayNumbers);
const copiedArrayNumbersSlice = arrayNumbers.slice();
console.log('copiedArrayNumbersSlice', copiedArrayNumbersSlice);
const copiedArrayNumbersSpread = [...arrayNumbers];
console.log('copiedArrayNumbersSpread', copiedArrayNumbersSpread);
const copiedArrayNumbersSpread2 = [...arrayNumbers, 7, 8, 9];
console.log('copiedArrayNumbersSpread2', copiedArrayNumbersSpread2);
const copiedArrayNumbersConcat = arrayNumbers.concat([7, 8, 9]);
console.log('copiedArrayNumbersConcat', copiedArrayNumbersConcat);
const copiedArrayNumbersConcat2 = arrayNumbers.concat(7, 8, 9);
console.log('copiedArrayNumbersConcat2', copiedArrayNumbersConcat2);
const copiedArrayNumbersConcat3 = arrayNumbers.concat(7, [8, 9]);
console.log('copiedArrayNumbersConcat3', copiedArrayNumbersConcat3);
const copiedArrayNumbersConcat4 = arrayNumbers.concat([7, [8, 9]]);
console.log('copiedArrayNumbersConcat4', copiedArrayNumbersConcat4);
const copiedArrayNumbersConcat5 = arrayNumbers.concat(7, [8, [9]]);
console.log('copiedArrayNumbersConcat5', copiedArrayNumbersConcat5);
const copyWithinArrayNumbers = arrayNumbers.copyWithin(0, 2, 4);
console.log('copyWithinArrayNumbers', copyWithinArrayNumbers);
arrayNumbers.fill('fe', 2, 4);
console.log('filledArrayNumbers', arrayNumbers);
