const number1 = 5;
const number2 = 2;
console.log('number1 = ', number1);
console.log('number2 = ', number2);
console.log('number1 + number2 = ', number1 + number2);
console.log('number1 - number2', number1 - number2);
console.log('number1 * number2', number1 * number2);
console.log('number1 / number2', number1 / number2);
console.log('number1 % number2', number1 % number2);
console.log('number1 ** number2', number1 ** number2);
console.log('Math.floor(number1 / number2)', Math.floor(number1 / number2));
console.log('Math.ceil(number1 / number2)', Math.ceil(number1 / number2));
console.log('Math.round(number1 / number2)', Math.round(number1 / number2));
const string1 = 'Hello';
const string2 = 'World';
console.log('string1 = ', string1);
console.log('string2 = ', string2);
console.log('string1 + string2 = ', string1 + string2);
console.log('string1 - number2 = ', string1 - number2);
console.log('string1 * number2 = ', string1 * number2);
console.log('string1 / number2 = ', string1 / number2);
console.log('string1 % number2 = ', string1 % number2);
console.log('string1 ** number2 = ', string1 ** number2);
const boolean1 = true;
const boolean2 = false;
console.log('boolean1 = ', boolean1);
console.log('boolean2 = ', boolean2);
console.log('boolean1 + boolean2 = ', boolean1 + boolean2);
console.log('boolean1 - boolean2 = ', boolean1 - boolean2);
console.log('boolean1 * boolean2 = ', boolean1 * boolean2);
console.log('boolean1 / boolean2 = ', boolean1 / boolean2);
console.log('boolean1 % boolean2 = ', boolean1 % boolean2);
console.log('boolean1 ** boolean2 = ', boolean1 ** boolean2);
const null1 = null;
const null2 = null;
console.log('null1 = ', null1);
console.log('null2 = ', null2);
console.log('null1 + null2 = ', null1 + null2);
console.log('null1 - null2 = ', null1 - null2);
console.log('null1 * null2 = ', null1 * null2);
console.log('null1 / null2 = ', null1 / null2);
console.log('null1 % null2 = ', null1 % null2);
console.log('null1 ** null2 = ', null1 ** null2);
const undefined1 = undefined;
const undefined2 = undefined;
console.log('undefined1 = ', undefined1);
console.log('undefined2 = ', undefined2);
console.log('undefined1 + undefined2 = ', undefined1 + undefined2);
console.log('undefined1 - undefined2 = ', undefined1 - undefined2);
console.log('undefined1 * undefined2 = ', undefined1 * undefined2);
console.log('undefined1 / undefined2 = ', undefined1 / undefined2);
console.log('undefined1 % undefined2 = ', undefined1 % undefined2);
console.log('undefined1 ** undefined2 = ', undefined1 ** undefined2);
console.log('null1 = ', null1);
console.log('undefined1 = ', undefined1);
console.log('null1 + undefined1 = ', null1 + undefined1);
console.log('null1 - undefined1 = ', null1 - undefined1);
console.log('null1 * undefined1 = ', null1 * undefined1);
console.log('null1 / undefined1 = ', null1 / undefined1);
console.log('null1 % undefined1 = ', null1 % undefined1);
console.log('null1 ** undefined1 = ', null1 ** undefined1);

console.log('-----different types-----');
console.log('number1 + string1 = ', number1 + string1);
console.log('number1 + boolean1 = ', number1 + boolean1);
console.log('number1 + null1 = ', number1 + null1);
console.log('number1 + undefined1 = ', number1 + undefined1);
console.log('string1 + boolean1 = ', string1 + boolean1);
console.log('string1 + null1 = ', string1 + null1);
console.log('string1 + undefined1 = ', string1 + undefined1);
console.log('boolean1 + null1 = ', boolean1 + null1);
console.log('boolean1 + undefined1 = ', boolean1 + undefined1);
console.log('null1 + undefined1 = ', null1 + undefined1);

// let sum = number1 + number2;
// let difference = number1 - number2;
// let product = number1 * number2;
// let quotient = number1 / number2;
// let remainder = number1 % number2;
// let exponent = number1 ** number2;
// let floor = Math.floor(number1 / number2);
// let ceil = Math.ceil(number1 / number2);
// let round = Math.round(number1 / number2);
